[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "public"
  framework = "react"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
